# Generated by Django 3.2.13 on 2022-06-10 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodworks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderrecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=30)),
                ('ordered_qty', models.CharField(max_length=30)),
                ('item_price', models.CharField(max_length=30)),
                ('total_payable', models.CharField(max_length=30)),
            ],
        ),
    ]
