# Generated by Django 3.2.13 on 2022-06-10 04:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodworks', '0002_orderrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrecord',
            name='order_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
